name: Release

on:
  push:
    branches:
    - add-vsixsigntool-nugget
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name : See inside folders
        run : cd && dir
